name: Build & Deploy Angular and  Java App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
      
      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout frontend code
      uses: actions/checkout@v4
      with:
        repository: edul77/angular-test
        token: ${{ secrets.PAT }}


# ───────────────────────────────────────────────────
    # Build frontend 
 # ───────────────────────────────────────────────────

     # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '18'

      # Step 3: Install dependencies and build Angular app
    - name: Install and build Angular
      run: |
          npm install -g @angular/cli
          npm install
          ng build --configuration production



  # ───────────────────────────────────────────────────
    # Configuring credentials
 # ───────────────────────────────────────────────────        

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


 # ───────────────────────────────────────────────────
    # Configuring credentials 
 # ───────────────────────────────────────────────────  

    - name: Upload frontend to s3
      run: |
          aws s3 cp ./dist/angular-conduit/* s3://fuck-buc/






          


   
         


          
          
          





